name             "php_imap"
maintainer       "Leonid Mamaev (adci)"
maintainer_email "leonid.mamaev@gmail.com"
license          ""
description      "Installs PHP IMAP extension"
version          "0.0.1"
