name             "phpapp"
maintainer       "Leonid Mamaev (adci)"
maintainer_email "leonid.mamaev@gmail.com"
license          "All rights reserved"
description      "Installs/Configures nginx, mysql, php-fpm"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"

depends "nginx"
depends "php"
depends "php-fpm"
depends "openssl"
depends "ohai"
depends "build-essential"
depends "percona"
depends "http_request"
